language: node_js
script: npm run test-coverage

services:
  - docker
  - redis-server
cache:
  apt: true
  directories:
    - node_modules
before_install:
  - npm install -g npm@3.10.3
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - ./scripts/docker/trigger.sh
node_js:
  - "4.4"
env:
  global:
    - CXX=g++-4.8
    - secure: "Zr1uClUBu7gVHP35ay6tvBqpO+hzYrU/AdIqdzhPHJVHTw3Tzhfwkyy1t1OZTmzuCkDqXILNfUMrVT4KKhRRX8b+qhN8NWLMloORo2Tyjveygd5mUdUwXfSg8uP9Bd4D26p0FClHkngeAXy1OiNXueLYBrY+7NyfjEGOxHUgjtMC4hG0a94U5VoLbQY9zaQjDSeKBIN0ZcL5Xpc4+gW6XAKG+LlGyz7bqWqcSYMILM3lPfLURlFOifVVWfEp1UJDedVjVqdtKy1B2G5E2kXQzTMDGoAc6xLjGcdoh/6D7Q5cdx8rZ2GuKL193wDf7KlWX0iUkzw8lh6GWtuZ3S+A642xzYAXywBUkUzQpura/ni7Evm0h8tOE3pu8r8bEI4HzodsMkrUFChg/7KaNloIkgZA9OWkx9w2ef1FplHGBvNNrULqt3kNKm+y95yCTTXZG+jWFlvtdmz3my7k/17wIu57b54cG8DLMh8q9yOA0yZpdrYgDWo6ggxdzFAVQkh+oID/JYXYRtv3V1T+0miA7KF0IGyXxaFZwi8dzGreXE+DKxzzfKdDVWGhD8kQb07XbJrE1NU/Uj06xHZDztgDYBmx92Te2MSvaYENomHP2Op/GIaItxwxKSleR6vYgfu4qi+1UFAugRZ447UQA2JK0XRyKcFC4haKg+6lbOMOkJk="
    - secure: "rkK/JBsw/FGnnMj8cATOpv82E7npkjbw5Ur1wFnCxsjK1n8d+CW0EZI56xG17xRKQksuUhVJ8BjDGVao65B4xcHAPMBFewVOmWnTEdSMWmR6VFgK/LqOdaDHMeKGzAgHvesLpxwg+fsFTYJtYAwJ8WIIYFGz2hgP/x7RqckLEEOVM3ohTpg6Dl1F0UTmLKXeSsaMzEcNdVYsQKjJ8kM8r5i8KN9zSTE3WBdW0Ip+u8K+PKjj2pFx/LBNPlW3OM3VUq7tzoL93Fnhq0c2GTPiFwyu7hGWlIfyCQ3fSkPz4rwZrj+QeIAVrqwZpVTIEzaGmNKoaHlELz66l2HUCyXiyQcPwK21WPzFWm8OwPMLlAF+PCETOC0LxKsqd0crKd4zRu12YFgcZr3GtqYEBXpvaZYAbp5ve5ohV5Foer4u+hZ75NLQFlgv6EVmJspxDJ+k/Wau5Mf98hbcKxQx/niAtQJMi3Z0CMPEuXuA37O/73+stb/jU460xAmez7vvkm4kE7A48ujqqTVizyxq+nX+iOAHuB4gWpXZi4HmVj82mCTRxYzVkSQl8B040MVa7m5nYSx03vJms8srHmK/AZxMPKQFnvWgR/7bCMXKGM5nHZ/0wSbw5+s49+pQggDL3Ku1fb+HByJa5JnpKf59k0mPpQE1VxK9x3NYZhMFe30vNKM="
    - secure: "u1XyAXDtJDtPVdEYE6uw9+pkRu4M3jo1dHzG4RBtyh1cD4WPzSC1mgY+wnRoC+RBJvnlSSZ6VqnIDGFIhIRAE90lbyTkf+K+p1pJ5WQ/m8cM4ZiYmVy3KDF5Fxy7T6vrOFryVhMHFVhWLjVwOWIsG02rkes01EzDQ+5Y5gQUl9zeqaTso0HpbqvDK7v0xVL7/YYpYKmMAF3AhZ9/rGbs7W8YzNkDCqLkVOhhVEwnfbufwjebgz3sGiEOP1YyYinhi7qTz11cBPollFn35kgxABX9Fw4gXa2Y+4n8cNdrwYWT/yg2unXbfopn6GaNJT1VdwJ4jhkGVzgbNKX3dQcMFafouv19wgpMgE3MOE/nGB870JVWI/Lyxhqz+JhT6R6iVHQYDQnbEs3Clc/WlfrWXxY2Nuwa5yXjuCV4DRBaZD030Zon+kKjnRXT+C8K3KfQtzfMK3ZHRuDdm/NNAKu+XDRwjWOcHz6UOLCKm7Pwk+Z0CxGyczearZ5H1wKGhs68K0Ny4ZtFVohd+SLmwVRYEuI0YCkX/SR6ll0/ro8c8NL0fYenTPfyhsctNEkNDxK0xcGKgemSiyelV8dnBdcM+S2hvvWLA6HAYLppCFbSFjaOh/TLuQAgrud6NFW3W1Fe6h9C4O0psKG1o4XDBr5vaVTO2f4GStretINc7zM94Lo="
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libxml2-dev
